branches: ["2.x", "3.x", "master"]
maintained_branches: ["3.x", "master"]
current_branch: "master"
dev_branch: "master"
dev_branch_alias: "4.x"
doc_dir: { "3.x": "Resources/doc/", "master": "docs/" }
