#!/usr/bin/env php
<?php
if (!file_exists(__DIR__.'/vendor/bin/phpunit')) {
    echo "Unable to find the `phpunit` script in `vendor/bin/phpunit`.\nPlease run `composer install` before running this command.\n";
    exit(1);
}
putenv('SYMFONY_PHPUNIT_DIR='.__DIR__.'/.phpunit');
require __DIR__.'/vendor/bin/phpunit';
