name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]

body:
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: x.y.z
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context about the bug (configs, logs, screenshots etc.)
