name: Feature Request
description: Suggest ideas for new features and improvements
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context about the feature request (e.g. screenshots, code snippets, etc.)
