<?php

namespace Nelmio\ApiDocBundle\Parser;


interface HandlerInterface
{
    /**
     * Parses the request object for a list of parameters that can be merged back into the parameters generated by
     * the root parser.
     *
     * @param string $className The name of the input class being parsed.
     * @param string $name The name of the parameter being examined.
     * @param array $params The list of parameters already parsed by the host parser.
     */
    public function handle($className, $name, $params);
}
