name: Dependabot update UI files

on: pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./utils

    permissions:
      contents: write

    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v7
        with:
          node-version: '22.x'
      - uses: pnpm/action-setup@v6
        with:
          package_json_file: utils/package.json
          cache: true
          cache_dependency_path: utils/pnpm-lock.yaml
      - run: pnpm install --ignore-scripts
      - name: Swagger UI
        run: pnpm run swagger
      - name: Redocly
        run: pnpm run redoc
      - name: Scalar
        run: pnpm run scalar
      - name: Stoplight
        run: pnpm run stoplight
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[dependabot-skip] Update UI files"
          branch: ${{ github.head_ref }}